apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
#postgres
- postgres/postgres-secrets.yaml
- postgres/postgres-volumes.yaml
- postgres/postgres-deployment.yaml
- postgres/postgres-service.yaml
#keycloak
- keycloak/keycloak-secrets.yaml
- keycloak/keycloak-configmap.yaml
- keycloak/keycloak-deployment.yaml
- keycloak/keycloak-service.yaml
- keycloak/keycloak-ingress.yaml