apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
  namespace: namespace-here
data:
  POSTGRES_DB: keycloak
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: adminPassword