apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: namespace-here
  labels:
    app: postgres
type: Opaque
data:
  username: YWRtaW4= #admin b64
  password: YWRtaW5QYXNzd29yZA== #adminPassword b64