apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-secret
  labels:
    app: keycloak
  namespace: namespace-here
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin
  KC_PROXY: edge
  KC_DB: keycloak
  KC_DB_URL: jdbc:postgresql://postgres.namespace-here/keycloak