apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: namespace-here
  labels:
    app: keycloak
type: Opaque
data:
  adminUsername: YWRtaW4= #admin b64
  adminPassword: YWRtaW4= #admin b64